/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package YahyaRaoIA;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author YahyaRao
 */
public class ComfortScreen extends javax.swing.JFrame {

    /**
     * Creates new form ComfortScreen
     */
    private final FinalScreen finalScreen = new FinalScreen();
    private MainScreen first = null;
    
     public static final String NOTCOMFORTABLE = "Not Comfortable";
    public static final String COMFORTABLE = "Casual";
    public static final String REGULAR = "Regular";
    public static final String REALLYCOMFORTABLE = "Really Comfortable";
    
    
      private OccasionScreen ninth;
    public ComfortScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deleteClothingButton = new javax.swing.JButton();
        namePanel = new javax.swing.JLabel();
        helloPannel = new javax.swing.JLabel();
        settingsButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        notComfortableButton = new javax.swing.JButton();
        comfortableButton = new javax.swing.JButton();
        regularButton = new javax.swing.JButton();
        reallyComfortableButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 2, 44));

        deleteClothingButton.setBackground(new java.awt.Color(220, 33, 26));
        deleteClothingButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        deleteClothingButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteClothingButton.setText("Log Out");
        deleteClothingButton.setBorder(null);
        deleteClothingButton.setMaximumSize(new java.awt.Dimension(100, 100));
        deleteClothingButton.setMinimumSize(new java.awt.Dimension(100, 100));
        deleteClothingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClothingButtonActionPerformed(evt);
            }
        });

        namePanel.setFont(new java.awt.Font("Helvetica Neue", 1, 44)); // NOI18N
        namePanel.setForeground(new java.awt.Color(255, 255, 255));
        namePanel.setText("Sabeen");

        helloPannel.setFont(new java.awt.Font("Helvetica Neue", 1, 44)); // NOI18N
        helloPannel.setForeground(new java.awt.Color(255, 255, 255));
        helloPannel.setText("Hello");

        settingsButton.setBackground(new java.awt.Color(0, 2, 44));
        settingsButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/YahyaRaoIA/aaaGEAR.png"))); // NOI18N
        settingsButton.setBorder(null);
        settingsButton.setMaximumSize(new java.awt.Dimension(100, 100));
        settingsButton.setMinimumSize(new java.awt.Dimension(100, 100));
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(75, 246, 215));
        jLabel4.setText("closet.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteClothingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namePanel)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(helloPannel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helloPannel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteClothingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(33, 0, 45));

        notComfortableButton.setBackground(new java.awt.Color(0, 2, 44));
        notComfortableButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        notComfortableButton.setForeground(new java.awt.Color(255, 255, 255));
        notComfortableButton.setText("Not Comfortable");
        notComfortableButton.setBorder(null);
        notComfortableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notComfortableButtonActionPerformed(evt);
            }
        });

        comfortableButton.setBackground(new java.awt.Color(0, 2, 44));
        comfortableButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        comfortableButton.setForeground(new java.awt.Color(255, 255, 255));
        comfortableButton.setText("Comfortable");
        comfortableButton.setBorder(null);
        comfortableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comfortableButtonActionPerformed(evt);
            }
        });

        regularButton.setBackground(new java.awt.Color(0, 2, 44));
        regularButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        regularButton.setForeground(new java.awt.Color(255, 255, 255));
        regularButton.setText("Regular");
        regularButton.setBorder(null);
        regularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularButtonActionPerformed(evt);
            }
        });

        reallyComfortableButton.setBackground(new java.awt.Color(0, 2, 44));
        reallyComfortableButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        reallyComfortableButton.setForeground(new java.awt.Color(255, 255, 255));
        reallyComfortableButton.setText("Really Comfortable");
        reallyComfortableButton.setBorder(null);
        reallyComfortableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reallyComfortableButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("What's The Occasion Today?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(notComfortableButton)
                        .addGap(18, 18, 18)
                        .addComponent(comfortableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(regularButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reallyComfortableButton))
                    .addComponent(jLabel1))
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(notComfortableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(comfortableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regularButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reallyComfortableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void createArticle (MainScreen f, OccasionScreen h){
        ninth = h;
        first = f;
        ninth.setVisible(false);
        this.setVisible(true);
    }



public void navigateNext(String filterBy) {
    
         //filter the articles array by selected weather.
    List<Article> filteredItemSoFar = this.first.getFiltered();
    List<Article> filtered = new ArrayList<>();
    System.out.println("Filter By: "+ filterBy);
    for (Article item: filteredItemSoFar) {
        if (item.getComfort().equalsIgnoreCase(filterBy)) {
            System.out.print(" Picked : " + item.toString());
            filtered.add(item);
        }
    }
    
    if (filtered.size()==0) {
        // todo: nothing left... show msg to user and go back...
        System.out.println("Nothing in the filtered list... go back.");
        this.setVisible(false);
        this.ninth.setVisible(true);
    }
    
    
    this.first.setFiltered(filtered);
    finalScreen.createArticle(this.first,this);
    this.setVisible(false);
}
 
    private void reallyComfortableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reallyComfortableButtonActionPerformed
        
         this.navigateNext(ComfortScreen.REALLYCOMFORTABLE);
    }//GEN-LAST:event_reallyComfortableButtonActionPerformed

    private void regularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularButtonActionPerformed
        // TODO add your handling code here:
        this.navigateNext(ComfortScreen.REGULAR);
    }//GEN-LAST:event_regularButtonActionPerformed

    private void notComfortableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notComfortableButtonActionPerformed
        // TODO add your handling code here:
        this.navigateNext(ComfortScreen.NOTCOMFORTABLE);
    }//GEN-LAST:event_notComfortableButtonActionPerformed

    private void comfortableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comfortableButtonActionPerformed
        // TODO add your handling code here:
        this.navigateNext(ComfortScreen.COMFORTABLE);
    }//GEN-LAST:event_comfortableButtonActionPerformed

    private void deleteClothingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClothingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteClothingButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ComfortScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ComfortScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ComfortScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ComfortScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ComfortScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comfortableButton;
    private javax.swing.JButton deleteClothingButton;
    private javax.swing.JLabel helloPannel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel namePanel;
    private javax.swing.JButton notComfortableButton;
    private javax.swing.JButton reallyComfortableButton;
    private javax.swing.JButton regularButton;
    private javax.swing.JButton settingsButton;
    // End of variables declaration//GEN-END:variables
}
