/*//GEN-FIRST:event_semicasualButtonActionPerformed
 * To change this license header, choose License Headers in Project Properties.//GEN-LAST:event_semicasualButtonActionPerformed
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package YahyaRaoIA;

import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author YahyaRao
 */
public class OccasionScreen extends javax.swing.JFrame {

    
    private MainScreen mainScreen;
    
    public static final String ATHOME = "At Home";
    public static final String CASUAL = "Casual";
    public static final String REGULAR = "Regular";
    public static final String SEMICASUAL = "Semi-Formal";
    public static final String FORMAL = "Formal";
    /**
     * Creates new form OccasionScreen
     */
    private final ComfortScreen comfortScreen = new ComfortScreen();
    private WeatherScreen weatherScreen;
    
    
    public OccasionScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deleteClothingButton = new javax.swing.JButton();
        namePanel = new javax.swing.JLabel();
        helloPannel = new javax.swing.JLabel();
        settingsButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        semicasualButton = new javax.swing.JButton();
        formalButton4 = new javax.swing.JButton();
        regularButton = new javax.swing.JButton();
        casualButton = new javax.swing.JButton();
        atHomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 2, 44));

        deleteClothingButton.setBackground(new java.awt.Color(220, 33, 26));
        deleteClothingButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        deleteClothingButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteClothingButton.setText("Log Out");
        deleteClothingButton.setBorder(null);
        deleteClothingButton.setMaximumSize(new java.awt.Dimension(100, 100));
        deleteClothingButton.setMinimumSize(new java.awt.Dimension(100, 100));
        deleteClothingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClothingButtonActionPerformed(evt);
            }
        });

        namePanel.setFont(new java.awt.Font("Helvetica Neue", 1, 44)); // NOI18N
        namePanel.setForeground(new java.awt.Color(255, 255, 255));
        namePanel.setText("Sabeen");

        helloPannel.setFont(new java.awt.Font("Helvetica Neue", 1, 44)); // NOI18N
        helloPannel.setForeground(new java.awt.Color(255, 255, 255));
        helloPannel.setText("Hello");

        settingsButton.setBackground(new java.awt.Color(0, 2, 44));
        settingsButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/YahyaRaoIA/aaaGEAR.png"))); // NOI18N
        settingsButton.setBorder(null);
        settingsButton.setMaximumSize(new java.awt.Dimension(100, 100));
        settingsButton.setMinimumSize(new java.awt.Dimension(100, 100));
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(75, 246, 215));
        jLabel4.setText("closet.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(helloPannel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteClothingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namePanel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helloPannel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteClothingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(33, 0, 45));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("What's The Occasion Today?");

        semicasualButton.setBackground(new java.awt.Color(0, 2, 44));
        semicasualButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        semicasualButton.setForeground(new java.awt.Color(255, 255, 255));
        semicasualButton.setText("Semi-Casual");
        semicasualButton.setBorder(null);
        semicasualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semicasualButtonActionPerformed(evt);
            }
        });

        formalButton4.setBackground(new java.awt.Color(0, 2, 44));
        formalButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        formalButton4.setForeground(new java.awt.Color(255, 255, 255));
        formalButton4.setText("Formal");
        formalButton4.setBorder(null);
        formalButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formalButton4ActionPerformed(evt);
            }
        });

        regularButton.setBackground(new java.awt.Color(0, 2, 44));
        regularButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        regularButton.setForeground(new java.awt.Color(255, 255, 255));
        regularButton.setText("Regual");
        regularButton.setBorder(null);
        regularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularButtonActionPerformed(evt);
            }
        });

        casualButton.setBackground(new java.awt.Color(0, 2, 44));
        casualButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        casualButton.setForeground(new java.awt.Color(255, 255, 255));
        casualButton.setText("Casual");
        casualButton.setBorder(null);
        casualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casualButtonActionPerformed(evt);
            }
        });

        atHomeButton.setBackground(new java.awt.Color(0, 2, 44));
        atHomeButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        atHomeButton.setForeground(new java.awt.Color(255, 255, 255));
        atHomeButton.setText("At Home");
        atHomeButton.setBorder(null);
        atHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atHomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(atHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(casualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(regularButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(semicasualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(formalButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(casualButton, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                        .addComponent(regularButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(semicasualButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formalButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(atHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void createArticle (MainScreen f, WeatherScreen g){
        weatherScreen = g;
        mainScreen = f;
        weatherScreen.setVisible(false);
        this.setVisible(true);
   }
   
   
   private void navigateNext(String filterBy) {
    //filter the articles array by selected weather.
    List<Article> filteredItemSoFar = this.mainScreen.getFiltered();
    List<Article> filtered = new ArrayList<>();
    System.out.println("Filter By: "+ filterBy);
    for (Article item: filteredItemSoFar) {
        if (item.getOccasion().equalsIgnoreCase(filterBy)) {
            System.out.print(" Picked:  " + item.toString());
            filtered.add(item);
        }
    }
    
    if (filtered.size()==0) {
        // todo: nothing left... show msg to user and go back...
        System.out.println("Nothing in the filtered list, go back");
        this.setVisible(false);
        this.weatherScreen.setVisible(true);
    }
    
    this.mainScreen.setFiltered(filtered);
    comfortScreen.createArticle(this.mainScreen,this);
    this.setVisible(false);
}

   
    private void semicasualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semicasualButtonActionPerformed
        // TODO add your handling code here:
        this.navigateNext(OccasionScreen.SEMICASUAL);
    }//GEN-LAST:event_semicasualButtonActionPerformed

    private void casualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casualButtonActionPerformed
        // TODO add your handling code here:
        this.navigateNext(OccasionScreen.CASUAL);
    }//GEN-LAST:event_casualButtonActionPerformed

    private void atHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atHomeButtonActionPerformed
        // TODO add your handling code here:
        this.navigateNext(OccasionScreen.ATHOME);
    }//GEN-LAST:event_atHomeButtonActionPerformed

    private void regularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularButtonActionPerformed
        // TODO add your handling code here:
        this.navigateNext(OccasionScreen.REGULAR);
    }//GEN-LAST:event_regularButtonActionPerformed

    private void formalButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formalButton4ActionPerformed
        // TODO add your handling code here:
        this.navigateNext(OccasionScreen.FORMAL);
    }//GEN-LAST:event_formalButton4ActionPerformed

    private void deleteClothingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClothingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteClothingButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OccasionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OccasionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OccasionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OccasionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OccasionScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atHomeButton;
    private javax.swing.JButton casualButton;
    private javax.swing.JButton deleteClothingButton;
    private javax.swing.JButton formalButton4;
    private javax.swing.JLabel helloPannel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel namePanel;
    private javax.swing.JButton regularButton;
    private javax.swing.JButton semicasualButton;
    private javax.swing.JButton settingsButton;
    // End of variables declaration//GEN-END:variables
}
