/*//GEN-LINE:variables
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package YahyaRaoIA;

/**
 *
 * @author YahyaRao
 */
public class WeatherScreen extends javax.swing.JFrame {

     private final OccasionScreen occasionScreen;
     
    public static final String SUNNY = "Sunny";
    public static final String RAINY = "Rainy";
    public static final String SNOWY = "Snowy";
    public static final String COLD = "Cold";
    public static final String WINDY = "Windy";
    public static final String CLEAR = "Clear";
   
 
     
/**
     * Creates new form WeatherScreen
     */
     private MainScreen first;  
        
        
    public WeatherScreen() {
        this.occasionScreen = new OccasionScreen();
        initComponents();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rainyButton = new javax.swing.JButton();
        snowyButton = new javax.swing.JButton();
        windyButton = new javax.swing.JButton();
        sunnyButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        coldButton1 = new javax.swing.JButton();
        infoPannel = new javax.swing.JPanel();
        deleteClothingButton = new javax.swing.JButton();
        namePanel = new javax.swing.JLabel();
        helloPannel = new javax.swing.JLabel();
        settingsButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 0, 45));
        setForeground(new java.awt.Color(33, 0, 45));

        jPanel1.setBackground(new java.awt.Color(33, 0, 45));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hows The Weather Today?");

        rainyButton.setBackground(new java.awt.Color(0, 2, 44));
        rainyButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        rainyButton.setForeground(new java.awt.Color(255, 255, 255));
        rainyButton.setText("Rainy");
        rainyButton.setBorder(null);
        rainyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rainyButtonActionPerformed(evt);
            }
        });

        snowyButton.setBackground(new java.awt.Color(0, 2, 44));
        snowyButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        snowyButton.setForeground(new java.awt.Color(255, 255, 255));
        snowyButton.setText("Snowy");
        snowyButton.setBorder(null);
        snowyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snowyButtonActionPerformed(evt);
            }
        });

        windyButton.setBackground(new java.awt.Color(0, 2, 44));
        windyButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        windyButton.setForeground(new java.awt.Color(255, 255, 255));
        windyButton.setText("Windy");
        windyButton.setBorder(null);
        windyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windyButtonActionPerformed(evt);
            }
        });

        sunnyButton.setBackground(new java.awt.Color(0, 2, 44));
        sunnyButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        sunnyButton.setForeground(new java.awt.Color(255, 255, 255));
        sunnyButton.setText("Sunny");
        sunnyButton.setBorder(null);
        sunnyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunnyButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(0, 2, 44));
        clearButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.setBorder(null);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        coldButton1.setBackground(new java.awt.Color(0, 2, 44));
        coldButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        coldButton1.setForeground(new java.awt.Color(255, 255, 255));
        coldButton1.setText("Cold");
        coldButton1.setBorder(null);
        coldButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(sunnyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rainyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snowyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coldButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(windyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sunnyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(rainyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(snowyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coldButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(windyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );

        infoPannel.setBackground(new java.awt.Color(0, 2, 44));
        infoPannel.setForeground(new java.awt.Color(35, 37, 54));

        deleteClothingButton.setBackground(new java.awt.Color(220, 33, 26));
        deleteClothingButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        deleteClothingButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteClothingButton.setText("Log Out");
        deleteClothingButton.setBorder(null);
        deleteClothingButton.setMaximumSize(new java.awt.Dimension(100, 100));
        deleteClothingButton.setMinimumSize(new java.awt.Dimension(100, 100));
        deleteClothingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClothingButtonActionPerformed(evt);
            }
        });

        namePanel.setFont(new java.awt.Font("Helvetica Neue", 1, 44)); // NOI18N
        namePanel.setForeground(new java.awt.Color(255, 255, 255));
        namePanel.setText("Sabeen");

        helloPannel.setFont(new java.awt.Font("Helvetica Neue", 1, 44)); // NOI18N
        helloPannel.setForeground(new java.awt.Color(255, 255, 255));
        helloPannel.setText("Hello");

        settingsButton.setBackground(new java.awt.Color(0, 2, 44));
        settingsButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/YahyaRaoIA/aaaGEAR.png"))); // NOI18N
        settingsButton.setBorder(null);
        settingsButton.setMaximumSize(new java.awt.Dimension(100, 100));
        settingsButton.setMinimumSize(new java.awt.Dimension(100, 100));
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(75, 246, 215));
        jLabel4.setText("closet.");

        javax.swing.GroupLayout infoPannelLayout = new javax.swing.GroupLayout(infoPannel);
        infoPannel.setLayout(infoPannelLayout);
        infoPannelLayout.setHorizontalGroup(
            infoPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPannelLayout.createSequentialGroup()
                        .addGroup(infoPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPannelLayout.createSequentialGroup()
                                .addComponent(helloPannel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(infoPannelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteClothingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(infoPannelLayout.createSequentialGroup()
                        .addComponent(namePanel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        infoPannelLayout.setVerticalGroup(
            infoPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helloPannel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteClothingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(infoPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void createArticle (MainScreen f){
        first = f;
        first.setVisible(false);
        this.setVisible(true);
    }


private void navigateToSeventh(String filterBy) {
    //filter the articles array by selected weather.
    Article[] clothing = this.first.getClothing();
    for ( int i=0; i<clothing.length && clothing[i]!=null; i++) {
        Article item = clothing[i];
        System.out.println("Filter By: "+ filterBy);
        if (item.getWarmth().equalsIgnoreCase(filterBy)) {
            System.out.print(" Picked:  " + item.toString());
            this.first.getFiltered().add(item);
        }
    }
    
    
    
    // if there's nothing in the filtered list... just let 
    if (this.first.getFiltered().isEmpty() ) {
        System.out.println("Nothing in the filtered list...  go back..");
        this.setVisible(false);
        this.first.setVisible(true);
    }
    
    // the user know and make them go back...
    occasionScreen.createArticle(this.first,this);
}


    private void sunnyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunnyButtonActionPerformed
        // TODO add your handling code here:
        this.navigateToSeventh(WeatherScreen.SUNNY);
        
    }//GEN-LAST:event_sunnyButtonActionPerformed

    private void rainyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rainyButtonActionPerformed
        // TODO add your handling code here:
         this.navigateToSeventh(WeatherScreen.RAINY);
    
    }//GEN-LAST:event_rainyButtonActionPerformed

    private void snowyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snowyButtonActionPerformed
        // TODO add your handling code here:
         this.navigateToSeventh(WeatherScreen.SNOWY);
       
    }//GEN-LAST:event_snowyButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
         this.navigateToSeventh(WeatherScreen.CLEAR);
       
    }//GEN-LAST:event_clearButtonActionPerformed

    private void windyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windyButtonActionPerformed
        // TODO add your handling code here:
         this.navigateToSeventh(WeatherScreen.WINDY);
      
    }//GEN-LAST:event_windyButtonActionPerformed

    private void coldButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldButton1ActionPerformed
        // TODO add your handling code here:
        this.navigateToSeventh(WeatherScreen.COLD);
    }//GEN-LAST:event_coldButton1ActionPerformed

    private void deleteClothingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClothingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteClothingButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(WeatherScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(WeatherScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(WeatherScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(WeatherScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new WeatherScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton coldButton1;
    private javax.swing.JButton deleteClothingButton;
    private javax.swing.JLabel helloPannel;
    private javax.swing.JPanel infoPannel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel namePanel;
    private javax.swing.JButton rainyButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JButton snowyButton;
    private javax.swing.JButton sunnyButton;
    private javax.swing.JButton windyButton;
    // End of variables declaration//GEN-END:variables
}
